name = "BayesianDETransformations"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Jingle Fu"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[compat]
DataFrames = "1.6"
CSV = "0.10"
BenchmarkTools = "1.5"
